# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The '2' in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
VAGRANTFILE_API_VERSION = '2'

Vagrant.configure('2') do |config|
  config.ssh.insert_key = false

  vms = {
    'lvs01' => {
      'os' => 'ubuntu/trusty64',
      'guest_http_port' => '8080',
      'guest_https_port' => '8443',
    },
    'lvs02' => {
      'os' => 'ubuntu/trusty64',
      'guest_http_port' => '8081',
      'guest_https_port' => '8444',
    },
    'www01' => {
      'os' => 'ubuntu/trusty64',
      'guest_http_port' => '8082',
      'guest_https_port' => '8445',
    },
    'www02' => {
      'os' => 'ubuntu/trusty64',
      'guest_http_port' => '8083',
      'guest_https_port' => '8446',
    },
  }

  vms.each do | name, vm_info |
    config.vm.define name do |vm_name|
      vm_name.vm.box = vm_info['os']
      vm_name.vm.network 'forwarded_port', guest: 80, host: vm_info['guest_http_port']
      vm_name.vm.network 'forwarded_port', guest: 443, host: vm_info['guest_https_port']
    end
  end
end
